In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
dataset = pd.read_csv('BostonHousing.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

Checking if there is any Missing Values

In [6]:
dataset.isnull().any()

crim       False
zn         False
indus      False
chas       False
nox        False
rm          True
age        False
dis        False
rad        False
tax        False
ptratio    False
b          False
lstat      False
medv       False
dtype: bool

RECTIFY the missing values

In [16]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(X[:,5:6])
X[:,5:6] = imputer.transform(X[:,5:6])

check for categorical data

In [18]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   crim     506 non-null    float64
 1   zn       506 non-null    float64
 2   indus    506 non-null    float64
 3   chas     506 non-null    int64  
 4   nox      506 non-null    float64
 5   rm       501 non-null    float64
 6   age      506 non-null    float64
 7   dis      506 non-null    float64
 8   rad      506 non-null    int64  
 9   tax      506 non-null    int64  
 10  ptratio  506 non-null    float64
 11  b        506 non-null    float64
 12  lstat    506 non-null    float64
 13  medv     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB


splitting into training and test data

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [20]:
X_train

array([[5.47900e-02, 3.30000e+01, 2.18000e+00, ..., 1.84000e+01,
        3.93360e+02, 8.93000e+00],
       [4.89822e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.75520e+02, 3.26000e+00],
       [3.51000e-02, 9.50000e+01, 2.68000e+00, ..., 1.47000e+01,
        3.92780e+02, 3.81000e+00],
       ...,
       [1.00000e-01, 3.40000e+01, 6.09000e+00, ..., 1.61000e+01,
        3.90430e+02, 4.86000e+00],
       [1.58760e-01, 0.00000e+00, 1.08100e+01, ..., 1.92000e+01,
        3.76940e+02, 9.88000e+00],
       [5.37200e-02, 0.00000e+00, 1.39200e+01, ..., 1.60000e+01,
        3.92850e+02, 7.39000e+00]])

In [21]:
X_test

array([[5.0230e-02, 3.5000e+01, 6.0600e+00, ..., 1.6900e+01, 3.9402e+02,
        1.2430e+01],
       [5.7834e-01, 2.0000e+01, 3.9700e+00, ..., 1.3000e+01, 3.8454e+02,
        7.4400e+00],
       [6.2630e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9199e+02,
        9.6700e+00],
       ...,
       [9.7617e-01, 0.0000e+00, 2.1890e+01, ..., 2.1200e+01, 2.6276e+02,
        1.7310e+01],
       [4.0974e+00, 0.0000e+00, 1.9580e+01, ..., 1.4700e+01, 3.9690e+02,
        2.6420e+01],
       [3.5510e-02, 2.5000e+01, 4.8600e+00, ..., 1.9000e+01, 3.9064e+02,
        7.5100e+00]])

In [22]:
y_train

array([28.4, 50. , 48.5, 19.4, 17.8, 22.3, 19.5, 12.1, 19.4, 50. , 22.8,
       19.9, 15.2, 23. , 33. , 32.4, 18.6, 23.8, 24.5, 34.6, 30.8,  8.1,
       22. , 15.6,  7.2, 23.2, 23.9, 24. , 22.6, 17.5, 23.3, 50. , 15.4,
       37.2, 25. ,  7. , 11. , 16. , 21.2, 30.3, 23.9, 50. , 23.3, 23.7,
       43.1, 28.2,  5.6, 17.8, 20.6, 19.5, 21.4, 50. , 34.9, 50. , 22. ,
       17.4, 24.7, 24.8, 18.2, 36.2, 30.5, 15.1, 14.1, 22. , 17.2, 21.7,
       34.7, 13.1, 23.1, 18.9, 34.9, 19.6, 18.7, 13.5, 16.1, 11.3, 16.2,
       22.4, 14.1, 17.9, 18.3, 23.3,  8.8, 13.1, 23.1, 21.4, 38.7, 32.2,
       23.1, 11.8, 20.9, 22.2, 18.9, 10.4, 23. , 33.3, 24.2, 21. , 18.5,
       17.4, 20.5, 13.3, 15.3, 23.7, 25. , 28. , 19.9, 25. , 31.6, 28.7,
        7. , 16.2, 19.3, 22.2, 12.6, 23.8, 13.9, 14.3, 20.4, 46.7, 15.2,
       41.7, 17.2, 32.5, 18.8, 10.9, 21.9, 17.8, 22.9, 20.4, 50. , 30.7,
       50. , 21.6, 13.6, 13.8, 11.7, 22.7, 20.2, 19.4, 37.6, 23.7,  7.2,
       14.6, 50. , 20.1, 19.4, 23.1, 16.5, 23.3, 21

In [23]:
y_test

array([17.1, 50. , 22.4, 15. , 21.1, 20. , 19.3, 17.2, 21.6, 12. , 43.5,
       31.5, 18.7, 19.5, 22. , 18.9, 20.6,  8.3, 13.8, 21.7, 21.4, 48.3,
       33.8, 22.8, 14.9, 31.2, 26.7, 24.7, 18.2, 29. , 14.4, 21.4, 16.8,
       16.5, 14.3, 36.2, 18. , 19.5, 20.6, 31.6, 21.2, 22.9, 19.1,  5. ,
       18.2, 22.6, 20.5, 14.2, 12.5,  8.4, 13.3,  8.7, 18.8, 13.4, 25.1,
       24.5, 16.1, 33.4, 25. , 22.8, 45.4, 29. , 24.1,  9.6, 27.9,  7.5,
       35.4, 20.1, 33.2, 14.8, 46. , 21.4,  5. , 25. , 14.6, 41.3, 20.9,
       13.4, 50. , 29.4, 24.8, 19.9, 12.8, 19.7, 20.6, 20. , 23.8, 23.9,
       24.6, 26.6, 29.6, 19.2, 13.4, 26.4, 23.7, 50. , 24.3, 24.8, 21.5,
       15.6, 15.6, 22.9])

training the model on training set

In [24]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

Predicitng the test Result

In [25]:
y_predict = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_predict.reshape(len(y_predict),1),y_test.reshape(len(y_test),1)),1))

[[20.27 17.1 ]
 [40.24 50.  ]
 [23.57 22.4 ]
 [25.38 15.  ]
 [20.66 21.1 ]
 [22.57 20.  ]
 [21.03 19.3 ]
 [14.62 17.2 ]
 [25.49 21.6 ]
 [12.02 12.  ]
 [39.04 43.5 ]
 [31.47 31.5 ]
 [20.68 18.7 ]
 [17.43 19.5 ]
 [29.07 22.  ]
 [18.41 18.9 ]
 [17.33 20.6 ]
 [13.52  8.3 ]
 [20.48 13.8 ]
 [22.03 21.7 ]
 [24.11 21.4 ]
 [36.64 48.3 ]
 [34.4  33.8 ]
 [24.88 22.8 ]
 [17.8  14.9 ]
 [28.9  31.2 ]
 [32.77 26.7 ]
 [24.69 24.7 ]
 [19.29 18.2 ]
 [31.42 29.  ]
 [ 8.66 14.4 ]
 [22.25 21.4 ]
 [20.35 16.8 ]
 [10.93 16.5 ]
 [17.32 14.3 ]
 [27.9  36.2 ]
 [18.87 18.  ]
 [20.26 19.5 ]
 [22.31 20.6 ]
 [32.17 31.6 ]
 [21.5  21.2 ]
 [22.76 22.9 ]
 [19.9  19.1 ]
 [ 6.99  5.  ]
 [18.64 18.2 ]
 [24.46 22.6 ]
 [20.26 20.5 ]
 [18.42 14.2 ]
 [19.41 12.5 ]
 [ 5.14  8.4 ]
 [13.85 13.3 ]
 [ 9.12  8.7 ]
 [20.83 18.8 ]
 [13.67 13.4 ]
 [29.7  25.1 ]
 [21.25 24.5 ]
 [22.09 16.1 ]
 [35.65 33.4 ]
 [29.5  25.  ]
 [28.41 22.8 ]
 [38.36 45.4 ]
 [32.22 29.  ]
 [29.93 24.1 ]
 [14.86  9.6 ]
 [32.69 27.9 ]
 [13.57  7.5 ]
 [34.19 35

Evaluate the Model

In [26]:
from sklearn.metrics import r2_score, mean_squared_error

print("R² Score:", r2_score(y_test, y_predict))
print("MSE:", mean_squared_error(y_test, y_predict))


R² Score: 0.7498324740542905
MSE: 22.79062349574424
